version: '3.7'

services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./docker-results/:/code/allure-results
      - ./screenshot/:/code/screenshot
    command: ["pytest", "-v", "-m space", "tests/test_page.py", "--alluredir=allure-results"]

