# -*- mode: ruby -*-
# vi: set ft=ruby :

NETWORK_BRIDGE = "enp4s0"
CPUS = 2
MEMORY = 4096

Vagrant.configure("2") do |config|

    # config.vm.boot_timeout = 600
    config.vm.box_check_update=false
    config.vm.box = "ubuntu/jammy64"

    config.vm.define "qa" do |qa|
        qa.vm.network "private_network", ip: "192.168.1.100"
        qa.vm.network "public_network", ip: "172.10.10.100", bridge: NETWORK_BRIDGE
        qa.vm.hostname = "qa-test-docker"
        qa.vm.synced_folder "src/", "/home/vagrant/src/"
        qa.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = MEMORY
            vb.cpus = CPUS
            vb.check_guest_additions = false
            vb.name = "qa-test-docker"
        end
    end
end