---
# tasks file for qa-test

 - name: Install required system packages
   ansible.builtin.include_tasks: tasks/packages.yml

 - name: Install Docker | docker-compose
   ansible.builtin.include_tasks: tasks/docker.yml

 - name: Clone Github repo
   ansible.builtin.include_tasks: tasks/git.yml

 - name: Running qa-tests | installation allure-server in docker
   ansible.builtin.include_tasks: tasks/run_test.yml
