---

- name: Update and upgrade apt packages
  ansible.builtin.apt:
    # upgrade: yes
    update_cache: true

- name: Install aptitude
  ansible.builtin.apt:
    name:
      - aptitude
    state: latest
    update_cache: true

- name: Install required system packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
#      - python3-dev
      - python3-virtualenv
    state: latest
    update_cache: true

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name:
      - docker==6.1.3
      - docker-compose
